### ISSUE TITLE
Summarize the feedback form

### ISSUE THREAD

**Issue by julbinb** [khoury-gsa/public#6]
Make a short summary, copy raw results

@julbinb and @mhyee

**Comment by julbinb** [comment]
Results are [here](https://docs.google.com/document/d/1FTHyBN5PGO8vyiWGBOI7Ks8w5IQ5og7fVJ9QUg3iiQ0/edit?usp=sharing)

I don't have the capacity to summarize free-form answers... We can either share as is, or if somebody feels like summarizing :)

**Comment by mhyee** [comment]
Thanks for getting most of this done!

I don't think we _need_ to summarize free-form answers, but I'll take a look later today.

**Comment by mhyee** [comment]
I made some tiny edits and formatting updates. Did not summarize any of the free-form answers: the responses are very different and detailed.

I think the summary form is ready to go out, along with the town hall summary #7.

**Comment by julbinb** [comment]
Thanks, looks good to me!
