### ISSUE TITLE
Make a quick summary of the Town Hall

### ISSUE THREAD

**Issue by julbinb** [khoury-gsa/public#7]
Probably with an anonymous form (optionally, name and email in case people are willing to follow-up) for gathering feedback about academic review experiences.

- [ ] create a form for academic review feedback
- [x] draft an email
- [ ] send the email

**Comment by julbinb** [comment]
@mister-walter prepared a [draft of the summary](https://docs.google.com/document/d/1NxYayykoX4A-OzNPj6E1qa2KF7evLmbHSbccjzXZaFg/edit?usp=sharing) (from Slack)

**Comment by julbinb** [comment]
I've made a separate issue for the academic review: https://github.com/khoury-gsa/public/issues/10

**Comment by julbinb** [comment]
PDF with the survey results, for attaching to the email.
[Fall 2020 Town Hall survey results.pdf](https://github.com/khoury-gsa/public/files/5749027/Fall.2020.Town.Hall.survey.results.pdf)

**Comment by mhyee** [comment]
Deleted the comment, because the link was publicly accessible.

[Here's a more restricted link, with the survey results.](https://drive.google.com/file/d/1Ob8dDglgG3l9AUOCuqJ17RsKaVaVqNpO/view?usp=sharing)

**Comment by mhyee** [comment]
Email sent.
